### ISSUE TITLE
Dependency on workspace crate are handled wrong

### ISSUE THREAD

**Issue by kegesch** [RustSec/cargo-audit#169]
If you have a dependency on another crate in your workspace and it has the same name as a cargo crate, `cargo audit` resolves it to cargo one and not the actual workspace crate. 

Example Cargo.toml: 
```toml
[dependencies]
generator = { path = "../generator" }
```
`audit` looks for vulnerabilities about [generator](https://crates.io/crates/generator). So basically the field `path` is not considered here.
